"""
This is a setup.py script generated by py2applet

Usage:
    python setup-catalog.py py2app
"""

from setuptools import setup

APP = ['src/tutcatalogpy/viewer/main.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['PySide2'],
    'iconfile': 'src/tutcatalogpy/resources/icons/viewer.icns',
    'plist': {
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleIdentifier': 'ro.borco.tutcatalogpy.viewer',
        'CFBundleVersion': '0.0.1',
        'NSHumanReadableCopyright': u'Copyright © 2021, Ioan Călin Borcoman, All Rights Reserved',
        'CFBundleTypeExtensions': [
            {
                'CFBundleTypeIconFile': 'viewer',
                'CFBundleTypeName': 'TutCatalog Info',
                'CFBundleTypeRole': 'Viewer',
                'LSHandlerRank': 'Owner',
                'LSItemContentTypes': [
                    'ro.borco.tutcatalogpy.viewer.tc',
                ]
            },
        ],
        'UTExportedTypeDeclarations': [
            {
                'UTTypeConformsTo': [
                    'public.plain-text'
                ],
                'UTTypeDescription': 'TutCatalog Info',
                'UTTypeIdentifier': 'ro.borco.tutcatalogpy.viewer.tc',
                'UTTypeTagSpecification': {
                    'public.filename-extension': 'tc',
                    'public.mime-type': 'text/plain',
                }
            }
        ],
    }
}

setup(
    name='TutCatalogPy Viewer',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
